# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='api.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\tapi.proto\x1a\x1cgoogle/protobuf/struct.proto\"\x1e\n\x0c\x42\x61seResponse\x12\x0e\n\x06status\x18\x01 \x01(\x08\"\x92\x01\n\x0eHistoryRequest\x12\x0e\n\x06source\x18\x01 \x01(\t\x12\x11\n\tsource_id\x18\x02 \x01(\t\x12\x0f\n\x07user_id\x18\x03 \x01(\t\x12\x11\n\ttimestamp\x18\x04 \x01(\x02\x12)\n\x08metadata\x18\x05 \x01(\x0b\x32\x17.google.protobuf.Struct\x12\x0e\n\x06\x61\x63tion\x18\x06 \x01(\t\"^\n\nPagination\x12\r\n\x05total\x18\x01 \x01(\x05\x12\x14\n\x0c\x63urrent_page\x18\x02 \x01(\x05\x12\x0f\n\x07\x64isplay\x18\x03 \x01(\x05\x12\r\n\x05start\x18\x04 \x01(\x02\x12\x0b\n\x03\x65nd\x18\x05 \x01(\x02\"S\n\x10HistoriesRequest\x12\x1e\n\x05query\x18\x01 \x01(\x0b\x32\x0f.HistoryRequest\x12\x1f\n\npagination\x18\x02 \x01(\x0b\x32\x0b.Pagination\"R\n\rListHistories\x12 \n\x07results\x18\x01 \x03(\x0b\x32\x0f.HistoryRequest\x12\x1f\n\npagination\x18\x02 \x01(\x0b\x32\x0b.Pagination2c\n\x0eHistoryService\x12&\n\x04push\x12\x0f.HistoryRequest\x1a\r.BaseResponse\x12)\n\x04pull\x12\x11.HistoriesRequest\x1a\x0e.ListHistoriesb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_struct__pb2.DESCRIPTOR,])




_BASERESPONSE = _descriptor.Descriptor(
  name='BaseResponse',
  full_name='BaseResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='BaseResponse.status', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=73,
)


_HISTORYREQUEST = _descriptor.Descriptor(
  name='HistoryRequest',
  full_name='HistoryRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='source', full_name='HistoryRequest.source', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='source_id', full_name='HistoryRequest.source_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='user_id', full_name='HistoryRequest.user_id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='HistoryRequest.timestamp', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='metadata', full_name='HistoryRequest.metadata', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='action', full_name='HistoryRequest.action', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=76,
  serialized_end=222,
)


_PAGINATION = _descriptor.Descriptor(
  name='Pagination',
  full_name='Pagination',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='total', full_name='Pagination.total', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='current_page', full_name='Pagination.current_page', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='display', full_name='Pagination.display', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='start', full_name='Pagination.start', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='end', full_name='Pagination.end', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=224,
  serialized_end=318,
)


_HISTORIESREQUEST = _descriptor.Descriptor(
  name='HistoriesRequest',
  full_name='HistoriesRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='query', full_name='HistoriesRequest.query', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pagination', full_name='HistoriesRequest.pagination', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=320,
  serialized_end=403,
)


_LISTHISTORIES = _descriptor.Descriptor(
  name='ListHistories',
  full_name='ListHistories',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='results', full_name='ListHistories.results', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pagination', full_name='ListHistories.pagination', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=405,
  serialized_end=487,
)

_HISTORYREQUEST.fields_by_name['metadata'].message_type = google_dot_protobuf_dot_struct__pb2._STRUCT
_HISTORIESREQUEST.fields_by_name['query'].message_type = _HISTORYREQUEST
_HISTORIESREQUEST.fields_by_name['pagination'].message_type = _PAGINATION
_LISTHISTORIES.fields_by_name['results'].message_type = _HISTORYREQUEST
_LISTHISTORIES.fields_by_name['pagination'].message_type = _PAGINATION
DESCRIPTOR.message_types_by_name['BaseResponse'] = _BASERESPONSE
DESCRIPTOR.message_types_by_name['HistoryRequest'] = _HISTORYREQUEST
DESCRIPTOR.message_types_by_name['Pagination'] = _PAGINATION
DESCRIPTOR.message_types_by_name['HistoriesRequest'] = _HISTORIESREQUEST
DESCRIPTOR.message_types_by_name['ListHistories'] = _LISTHISTORIES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BaseResponse = _reflection.GeneratedProtocolMessageType('BaseResponse', (_message.Message,), dict(
  DESCRIPTOR = _BASERESPONSE,
  __module__ = 'api_pb2'
  # @@protoc_insertion_point(class_scope:BaseResponse)
  ))
_sym_db.RegisterMessage(BaseResponse)

HistoryRequest = _reflection.GeneratedProtocolMessageType('HistoryRequest', (_message.Message,), dict(
  DESCRIPTOR = _HISTORYREQUEST,
  __module__ = 'api_pb2'
  # @@protoc_insertion_point(class_scope:HistoryRequest)
  ))
_sym_db.RegisterMessage(HistoryRequest)

Pagination = _reflection.GeneratedProtocolMessageType('Pagination', (_message.Message,), dict(
  DESCRIPTOR = _PAGINATION,
  __module__ = 'api_pb2'
  # @@protoc_insertion_point(class_scope:Pagination)
  ))
_sym_db.RegisterMessage(Pagination)

HistoriesRequest = _reflection.GeneratedProtocolMessageType('HistoriesRequest', (_message.Message,), dict(
  DESCRIPTOR = _HISTORIESREQUEST,
  __module__ = 'api_pb2'
  # @@protoc_insertion_point(class_scope:HistoriesRequest)
  ))
_sym_db.RegisterMessage(HistoriesRequest)

ListHistories = _reflection.GeneratedProtocolMessageType('ListHistories', (_message.Message,), dict(
  DESCRIPTOR = _LISTHISTORIES,
  __module__ = 'api_pb2'
  # @@protoc_insertion_point(class_scope:ListHistories)
  ))
_sym_db.RegisterMessage(ListHistories)



_HISTORYSERVICE = _descriptor.ServiceDescriptor(
  name='HistoryService',
  full_name='HistoryService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=489,
  serialized_end=588,
  methods=[
  _descriptor.MethodDescriptor(
    name='push',
    full_name='HistoryService.push',
    index=0,
    containing_service=None,
    input_type=_HISTORYREQUEST,
    output_type=_BASERESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='pull',
    full_name='HistoryService.pull',
    index=1,
    containing_service=None,
    input_type=_HISTORIESREQUEST,
    output_type=_LISTHISTORIES,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_HISTORYSERVICE)

DESCRIPTOR.services_by_name['HistoryService'] = _HISTORYSERVICE

# @@protoc_insertion_point(module_scope)
